version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # adjust if you use a different version
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Running main.py...
      - python main.py

artifacts:
  files:
    - '**/*'
